name: Build UACME on Release or Manually

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        shell: pwsh
        run: |
          # 使用 vswhere 查找最新安装的 Visual Studio 路径
          $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
                      -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          if (-not $vsPath) {
              Write-Error "未找到 Visual Studio 安装路径，请检查 VS 是否已安装。"
              exit 1
          }
          # 拼接 MSBuild.exe 的完整路径
          $msbuildExe = Join-Path $vsPath "MSBuild\Current\Bin\MSBuild.exe"
          Write-Host "Found MSBuild at: $msbuildExe"
          # 将 MSBuild.exe 路径保存为环境文件，供后续步骤使用
          $envFilePath = [System.Environment]::GetEnvironmentVariable('GITHUB_ENV')
          "$msbuildExe" | Out-File -FilePath $envFilePath -Encoding utf8 -Append

      - name: Build Solution for ${{ matrix.platform }}
        shell: pwsh
        run: |
          # 设置解决方案文件的相对路径，根据项目实际情况修改
          $solutionPath = "Source\UACME.sln"
          if (-not (Test-Path $solutionPath)) {
              Write-Error "未在路径 $solutionPath 找到解决方案文件。请确认路径是否正确。"
              exit 1
          }
          # 获取 MSBuild.exe 路径
          $msbuildExe = $env:MSBUILD_PATH
          # 编译解决方案，构建 Release 版本，指定平台
          & $msbuildExe $solutionPath /p:Configuration=Release /p:Platform=${{ matrix.platform }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UACME-executable-${{ matrix.platform }}-${{ github.run_id }}
          # 修改为你项目中编译产物实际存放的路径
          path: Source\Akagi\output\**\*.exe
