name: Build UACME on Release or Manually

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 提供的 Windows 环境
    strategy:
      matrix:
        architecture: [x86, x64]  # 32位和64位架构的矩阵

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 获取仓库代码

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1  # 设置 Visual Studio 编译环境
        with:
          vs-version: 'latest'  # 使用最新版本的 Visual Studio

      - name: Build Akatsuki project for ${{ matrix.architecture }}
        run: |
          echo "Building Akatsuki for architecture: ${{ matrix.architecture }}"
          # 使用 MSBuild 来编译项目，设置平台架构
          msbuild "Akatsuki\Akatsuki.vcxproj" /p:Configuration=Release /p:Platform=${{ matrix.architecture }} /p:PlatformToolset=v142
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Akatsuki-Build-${{ matrix.architecture }}
          path: |
            Akatsuki/bin/${{ matrix.architecture }}/Release/*
